### ISSUE TITLE
Endpoint /products/stemcell/associations isn't working

### ISSUE THREAD

**Issue by erboucherie** [pacphi/cf-butler#383]
Hello @pacphi , we are are very happy to use your applications , but found some issue on several endpoints .
One of them is **/stemcell/associations** which fails .
I look at the code , and i guess this is due to the om version check which misses some token .
Thanks in advance if you can have a look .
Best regards
Eric

**Comment by pacphi** [comment]
@erboucherie Would you share a few details of your environment?  What version of Operations Manager (OM) is up-and-running?  What are some of the tile and stemcell versions you have installed on inspection from (OM administrator interface)?

Admittedly it's been awhile since this logic was implemented. It followed guidance from the [OM 2.7 API docs](https://docs.pivotal.io/platform/2-7/opsman-api). I note layout changes from [OM 2.9 API docs](https://docs.pivotal.io/platform/2-9/opsman-api) onward.

If you look closely at https://docs.pivotal.io/platform/2-7/opsman-api/#info and https://docs.pivotal.io/platform/2-9/opsman-api/#tag/Info, both suggest the version is returned formatted something like "2.5.0-build.79".  And here, https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/client/OpsmanClient.java#L68 is where we obtain the version.  And here is where we make a decision whether we can fetch the stemcell associations, https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/client/OpsmanClient.java#L98.

I wonder if the version when converted to a Double value is bombing out due to the String format?  Perhaps we need to adjust the filter?  Or provide a convenience method off of [OmInfo](https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/domain/product/OmInfo.java) to return just the major dot minor version as a Double value.

If you would, please just `curl` your OM endpoint `/api/v0/info` and let me know what you see returned.  (Also please validate whether you can do this without an auth token -- that would represent a significant change).

**Comment by erboucherie** [comment]
Hi @pacphi . Thanks for answering so quickly .
We are using Opsman 2.10 , and here is the curl output (i was mistaken when saying that this was needing a token !)
`curl https://opsmanager-ee-qvi.af-klm.com/api/v0/info
{"info":{"version":"2.10"}}`

And here is a sample of the /api/v0/stemcell_associations from Opsmanager interface  : 
`{"products":[{"guid":"p-bosh-68915bd4a43738cbfce3","identifier":"p-bosh","label":"BOSH Director","staged_product_version":"2.10.14-build.248","deployed_product_version":"2.10.14-build.248","is_staged_for_deletion":false,"staged_stemcells":[{"os":"ubuntu-xenial","version":"621.130"}],"deployed_stemcells":[{"os":"ubuntu-xenial","version":"621.130"}],"available_stemcells":[{"os":"ubuntu-xenial","version":"621.130"}],"required_stemcells":[{"os":"ubuntu-xenial","version":"621.130","enable_patch_security_updates":false}]},{"guid":"cf-3d401a868aff83516641","identifier":"cf","label":"VMware Tanzu Application `

Hope it helps
Eric

**Comment by pacphi** [comment]
Another question.  How are you authenticating?  E.g., with username/password or client_id/client_secret.

I made a recent change to support the latter which may have impacted the function of the former.

In this case: all `/products/*` endpoints would be affected.  

> See [OpsmanTokenProvider](https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/client/OpsmanAccessTokenProvider.java#L39) and [OpsmanClient](https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/client/OpsmanClient.java#L101).

**Comment by erboucherie** [comment]
Yes indeed you made that change on my request (thanks for that) . We use client_id/client_secret for Opsman authentication .

**Comment by pacphi** [comment]
So, I'm going to share a branch for you to try [here](https://github.com/pacphi/cf-butler/tree/issue-383).

Here's the [PR](https://github.com/pacphi/cf-butler/pull/385).  You can see the [changes](https://github.com/pacphi/cf-butler/pull/385/commits/b1c9be307256e59673669162c10df541da75940b) I intend to introduce.  

Clone, checkout the branch, build it, then cf push.  Let me know if it has any positive impact for you. I need to prep a 2.10 environment to perform a proper integration test.

**Comment by pacphi** [comment]
I ran an integration test against an OM instance where the version of OM deployed was `2.10.13-build.243` and confirmed the fixes on this branch function as desired.

**Comment by erboucherie** [comment]
Hi @pacphi , yes i just tested it and it works like a charm !
Thanks again to be so reactive .
Best regards
Eric

**Comment by pacphi** [comment]
Endpoints for retrieving stemcell _assignments_ and _associations_ both function as desired.  But I am going to leave this branch open until I've solved for `GET /products/metrics` tile metadata reporting inconsistencies.

**Comment by pacphi** [comment]
Closed with 5b00450b4cad9560719500f0e3457ec97d621ea0.
