### ISSUE TITLE
Is StopApplicationPolicy functioning correctly?

### ISSUE THREAD

**Issue by erboucherie** [pacphi/cf-butler#388]
Hello @pacphi , we are trying to put in place some policies , to stop old applications (which have not been pushed since a long period) .
I took as a base example the policy file cf-butler-sample-config/blob/master/stop-applications-policy-sample-AP.json .
Mine is the following :
`{
    "description":"Stop applications that were last_pushed 1 months earlier than now",
    "operation":"stop",
    "state":"started",
    "options":{
       "from-duration":"P30D"
    }
 }`

But the task always tell me that 0 applications have been stopped despite that i see at least one app eligible to be stopped : 

> "AOS","AJSpace","ca3f26b0-2c64-4b0b-b346-0a24e3decf0b","springmusic-test-appmetrics","java","v4.36",,"cflinuxfs3","1","1","0.3059712","0.16539648","springtmusic-appmetrics.shared-ee-qvi.af-klm.com","2021-05-04T12:58:15","audit.app.start","62c1f89e-ab7b-4d87-86ce-e5f280f88b40","2021-09-02T12:02:31","started","Minor Release","2021-07-27T00:00","4.41","https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.41"

Any idea what i did wrong ?
I looked at the code , but difficult to see where the test to the "Last Pushed Date" date is made as a filter .
Thanks again if you can help ,
Eric

**Comment by pacphi** [comment]
The filter(s) for `ApplicationPolicy` are here

- https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/repository/R2dbcAppDetailRepository.java#L55
- https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/repository/R2dbcAppDetailRepository.java#L80

and likewise for `ServiceInstancePolicy`

- https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/repository/R2dbcServiceInstanceDetailRepository.java#L64

These filters rely on the capture of event data associated with an AI or SI which happens on collection.  

- https://github.com/pacphi/cf-butler/blob/master/src/main/java/io/pivotal/cfapp/task/AppDetailTask.java#L93
  - https://github.com/pacphi/cf-butler/blob/4597b19085f874af8b3f6dce870c78303de0353a/src/main/java/io/pivotal/cfapp/task/AppDetailTask.java#L144
  
 - https://github.com/pacphi/cf-butler/blob/4597b19085f874af8b3f6dce870c78303de0353a/src/main/java/io/pivotal/cfapp/task/ServiceInstanceDetailTask.java#L84
 
I don't know if you caught it, but in the filters for `AppPolicy` we use `last_event_time` rather than `last_pushed`.  This was a choice based on potential that the app instance could have crashed and been re-started.  I wonder if it makes sense in the policy definition to allow for you to specify whether you want to use `last_event_time` or `last_pushed`, defaulting to the former for consistency/compatibility's sake?
 
Have a go updating the filter logic yourself, and let me know what you find out.

**Comment by erboucherie** [comment]
Thank you very much for this very detailed explanation . Now i understand why my application is not stopped based on the `last_event_time` rather than the `last_pushed` which is in the description of the file i took as a basis .
In our thought , `last_pushed` was most representing the LCM of the application , and so we could deduce that an application is living or not .
But now that this is well understood how it works , it deoends on us what we will choose .
Thanks again

**Comment by pacphi** [comment]
Closing
